-- Repatch From Layer
-- Reads exported grandMA2 fixture-layer XML files, and writes a macro-pool XML
-- containing a Repatch macro (every fixture moved to the address the XML says)
-- and a Restore macro (every fixture moved back to where it is right now).
-- The plugin never changes the patch itself. You import the macro and run it.
-- UI text is English; comments are English.
-- Target version: grandMA2 3.9.60
--
-- Design (settled via /grill-me, then verified on a 3.9.60 console with a
-- throwaway probe plugin; see the "Verified on console" notes below):
--
--   Input   <path>/fixture_layers/<name>.xml, and <name><n>.xml for n = 1..64
--           so that a "...-LAYER-" prefix picks up every layer in one run.
--   Output  <path>/macros/<name>.xml, imported by hand into the Macro pool.
--
--   Fixtures are matched by fixture_id ONLY. The console reports ChaId as "-"
--   on this kind of show and the console's own layer export omits channel_id
--   entirely, so Channel ID is not a usable key.
--
--   A fixture's start address is the SMALLEST <Address> under it. Subfixture
--   index order does NOT follow address order (a TB5's <SubFixture index="0">
--   was the ninth address), so "first subfixture" would be wrong. All 62 TB5s
--   in the reference show share one offset pattern relative to that minimum,
--   which is why one Assign at the start address rebuilds every instance.
--
-- Address encoding (verified against 100 fixtures cross-checked with a macro
-- generated by GMA Toolbox for the same rig):
--       <Address> is the 1-based absolute DMX channel across all universes
--       universe = (Address - 1) // 512 + 1
--       address  = (Address - 1) %  512 + 1        e.g. 51201 -> 101.001
--
-- Verified on console (grandMA2 3.9.60 onPC):
--   * "Assign Fixture n At Dmx u.a" REPLACES the fixture's patch. The reverse
--     phrasing "Assign Dmx u.a At Fixture n" adds a multipatch instead, so the
--     order of the two objects in that command is not cosmetic.
--   * gma.show.property.get(handle, "patch") returns a string like "101.001",
--     and "(-)" when the fixture is unpatched.
--   * io.open(..., "w") works, which is what makes the macro-XML output viable.
--   * "Store Macro <n>.<line>" does NOT create macro lines - building a macro
--     that way produced a CMD_MACRO object with zero children. That is why the
--     output is an importable XML file rather than a macro built in place.
--   * "Delete Dmx u.a" unpatches whatever occupies that address and keeps all
--     programming, which is how the Restore macro returns a fixture to having
--     no patch. Do not "simplify" it to "Delete Fixture n": that deletes the
--     fixture along with everything programmed into it.
--
-- Deliberately out of scope: creating fixtures, changing fixture types, 3D
-- position, groups, fixture/channel IDs, multi-break fixtures and multipatch.
-- Positions are parsed anyway so a future plugin can reuse this parser.

local PLUGIN_TITLE = "Repatch From Layer"

-- Set true to echo per-fixture detail to the System Monitor.
local DEBUG = false

-- Console folder layout. Export Layer writes into fixture_layers, and the Macro
-- pool imports from macros; neither lives in importexport.
local LAYER_DIR = "/fixture_layers/"
local MACRO_DIR = "/macros/"

-- Highest <prefix><n>.xml probed when the entered name is a layer prefix.
local MAX_LAYER_SCAN = 64

-- What the console returns for a fixture that has no patch.
local UNPATCHED = "(-)"

-- Prepended to the generated file name and to both macro names, so anything
-- this plugin produced is recognisable at a glance in the macros folder and in
-- the Macro pool.
local OUTPUT_PREFIX = "NEW_PATCH_"

-- Wrapped around the generated macros, mirroring what GMA Toolbox emits: it
-- shows each command's response while the macro runs.
local MACRO_HEAD = 'Menu On "CommandlineResponse"'
local MACRO_TAIL = 'Menu Off "CommandlineResponse"'

local O = gma and gma.show.getobj
local P = gma and gma.show.property

-- ─── pure logic (no gma, unit-testable offline) ───────────────

local M = {}

M.OUTPUT_PREFIX = OUTPUT_PREFIX

-- Absolute 1-based DMX channel -> "universe.address", or nil when unpatched.
function M.decode_address(abs)
    abs = tonumber(abs)
    if not abs or abs <= 0 then return nil end
    local universe = math.floor((abs - 1) / 512) + 1
    local address  = ((abs - 1) % 512) + 1
    return string.format("%d.%03d", universe, address), universe, address
end

function M.xml_escape(s)
    s = tostring(s or "")
    s = s:gsub("&", "&amp;")
    s = s:gsub("<", "&lt;")
    s = s:gsub(">", "&gt;")
    s = s:gsub('"', "&quot;")
    s = s:gsub("'", "&apos;")
    return s
end

-- Parse one exported layer file into a list of fixture records.
--
-- Each record: id, name, ftype, instances, addresses (absolute, as found),
-- start (smallest non-zero absolute address, nil when fully unpatched),
-- multibreak (a <Patch> holding more than one <Address>), pos (placeholder for
-- a future position plugin; nil when the file carries no coordinates).
function M.parse_layer(xml)
    local fixtures = {}
    if type(xml) ~= "string" then return fixtures, nil end

    local layer_name = xml:match('<Layer[^>]-name="([^"]*)"')

    for attrs, body in xml:gmatch("<Fixture([^>]*)>(.-)</Fixture>") do
        local id = tonumber(attrs:match('fixture_id="(%d+)"'))
        if id then
            local addresses, zeros, start = {}, 0, nil
            for a in body:gmatch("<Address>%s*(%d+)%s*</Address>") do
                local n = tonumber(a)
                addresses[#addresses + 1] = n
                if n == 0 then
                    zeros = zeros + 1
                elseif (not start) or n < start then
                    start = n
                end
            end

            -- One <Patch> per break. More addresses than <Patch> blocks means a
            -- fixture whose breaks are patched independently, which a single
            -- start address cannot describe.
            local patch_blocks = 0
            for _ in body:gmatch("<Patch>") do patch_blocks = patch_blocks + 1 end

            local instances = 0
            for _ in body:gmatch("<SubFixture") do instances = instances + 1 end

            local px, py, pz = body:match(
                '<Location x="([%-%d%.]+)" y="([%-%d%.]+)" z="([%-%d%.]+)"')
            local rx, ry, rz = body:match(
                '<Rotation x="([%-%d%.]+)" y="([%-%d%.]+)" z="([%-%d%.]+)"')

            fixtures[#fixtures + 1] = {
                id         = id,
                name       = attrs:match('name="([^"]*)"'),
                ftype      = body:match('<FixtureType name="([^"]*)"'),
                instances  = instances,
                addresses  = addresses,
                zeros      = zeros,
                start      = start,
                multibreak = #addresses > patch_blocks,
                layer      = layer_name,
                pos        = px and { x = px, y = py, z = pz,
                                      rx = rx, ry = ry, rz = rz } or nil,
            }
        end
    end

    return fixtures, layer_name
end

-- Merge the per-file fixture lists into one id-ordered list.
-- A fixture_id belongs to exactly one layer, so a repeat means the same layer
-- was read twice; the first occurrence wins and the rest are counted.
function M.merge(lists)
    local seen, merged, duplicates = {}, {}, 0
    for _, list in ipairs(lists) do
        for _, f in ipairs(list) do
            if seen[f.id] then
                duplicates = duplicates + 1
            else
                seen[f.id] = true
                merged[#merged + 1] = f
            end
        end
    end
    table.sort(merged, function(a, b) return a.id < b.id end)
    return merged, duplicates
end

-- Split the merged list into what can be repatched and what cannot.
function M.classify(fixtures)
    local usable, unpatched, multibreak = {}, {}, {}
    for _, f in ipairs(fixtures) do
        if f.multibreak then
            multibreak[#multibreak + 1] = f
        elseif f.start then
            usable[#usable + 1] = f
        else
            unpatched[#unpatched + 1] = f
        end
    end
    return usable, unpatched, multibreak
end

function M.repatch_line(id, dmx)
    return string.format("Assign Fixture %d At Dmx %s", id, dmx)
end

-- Undo for a fixture that had no patch before the repatch macro ran: deleting
-- the DMX address unpatches whatever sits on it while leaving all programming
-- intact. Note it deletes the ADDRESS, not the fixture - "Delete Fixture n"
-- would erase the fixture and everything programmed into it.
--
-- Two known edges, both accepted rather than guessed at:
--   * If another fixture shares this address it is unpatched too. Duplicate
--     addresses are allowed on purpose here, so this is left alone.
--   * On a multi-instance fixture only the start address is deleted. Whether
--     that releases every instance is unverified on console.
function M.unpatch_line(dmx)
    return string.format("Delete Dmx %s /nc", dmx)
end

-- Full snapshot: one line per usable fixture, whether or not this console
-- currently agrees, so the macro can be carried to another console unchanged.
function M.repatch_lines(usable)
    local lines = {}
    for _, f in ipairs(usable) do
        lines[#lines + 1] = M.repatch_line(f.id, M.decode_address(f.start))
    end
    return lines
end

-- current = { [fixture_id] = "101.001" | "(-)" | nil }
--
-- Three cases, in the order they are tested:
--   nil    the fixture is not on this console, so there is no state to restore
--          - reported as skipped rather than guessed at
--   "(-)"  the fixture exists but is unpatched, so the undo is to delete the
--          address the repatch macro will have put it on
--   else   an ordinary address, restored with the same Assign the repatch uses
--
-- Returns the lines, the skipped fixtures, and how many of the lines unpatch.
function M.restore_lines(usable, current)
    local lines, skipped, unpatches = {}, {}, 0
    for _, f in ipairs(usable) do
        local at = current[f.id]
        if at == nil then
            skipped[#skipped + 1] = f
        elseif at ~= UNPATCHED and at ~= "" then
            lines[#lines + 1] = M.repatch_line(f.id, at)
        else
            lines[#lines + 1] = M.unpatch_line(M.decode_address(f.start))
            unpatches = unpatches + 1
        end
    end
    return lines, skipped, unpatches
end

-- macros = { { name = ..., info = ..., lines = { "..." } } }
function M.macro_xml(macros)
    local t = {}
    t[#t + 1] = '<?xml version="1.0" encoding="utf-8"?>'
    t[#t + 1] = '<MA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ' ..
                'xmlns="http://schemas.malighting.de/grandma2/xml/MA" ' ..
                'xsi:schemaLocation="http://schemas.malighting.de/grandma2/xml/MA ' ..
                'http://schemas.malighting.de/grandma2/xml/3.9.60/MA.xsd" ' ..
                'major_vers="3" minor_vers="9" stream_vers="60">'

    for mi, macro in ipairs(macros) do
        t[#t + 1] = string.format('\t<Macro index="%d" name="%s">',
            mi - 1, M.xml_escape(macro.name))
        if macro.info then
            t[#t + 1] = string.format('\t\t<InfoItems><Info>%s</Info></InfoItems>',
                M.xml_escape(macro.info))
        end

        local all = { MACRO_HEAD }
        for _, line in ipairs(macro.lines) do all[#all + 1] = line end
        all[#all + 1] = MACRO_TAIL

        for li, line in ipairs(all) do
            t[#t + 1] = string.format(
                '\t\t<Macroline index="%d" delay="0.01"><text>%s</text></Macroline>',
                li - 1, M.xml_escape(line))
        end
        t[#t + 1] = '\t</Macro>'
    end

    t[#t + 1] = '</MA>'
    return table.concat(t, "\n") .. "\n"
end

-- Trim, drop a typed ".xml", and reject anything that would escape the folder.
function M.clean_name(s)
    s = tostring(s or ""):gsub("^%s+", ""):gsub("%s+$", "")
    s = s:gsub("%.[xX][mM][lL]$", "")
    if s:find("[/\\]") or s:find("%.%.") then return nil end
    return s
end

-- Default output file name for a given input name or prefix: the source name
-- with any trailing "-LAYER-" removed, carrying the studio prefix.
function M.default_output_name(input)
    local base = input:gsub("[%s%-_]*[Ll][Aa][Yy][Ee][Rr][%s%-_]*$", "")
    base = base:gsub("[%s%-_]+$", "")
    if base == "" then base = input end
    return M.OUTPUT_PREFIX .. base
end

function M.summary_text(s)
    local lines = {
        "Files read:      " .. s.files,
        "Fixtures in XML: " .. s.total,
        "",
        "  repatchable:   " .. s.usable,
        "  unpatched:     " .. s.unpatched .. "   (Address 0, no line emitted)",
        "  multi-break:   " .. s.multibreak .. "   (skipped)",
    }
    if s.duplicates > 0 then
        lines[#lines + 1] = "  duplicate ids: " .. s.duplicates .. "   (first kept)"
    end
    lines[#lines + 1] = ""
    lines[#lines + 1] = "On this console:"
    lines[#lines + 1] = "  matched:       " .. s.matched
    lines[#lines + 1] = "  not found:     " .. s.missing .. "   (still in the macro)"
    lines[#lines + 1] = ""
    lines[#lines + 1] = "Macro 1 Repatch: " .. s.repatch_lines .. " lines"
    lines[#lines + 1] = "Macro 2 Restore: " .. s.restore_lines .. " lines"
    if s.restore_unpatches > 0 then
        lines[#lines + 1] = "  " .. s.restore_unpatches ..
            " of them unpatch (fixture has no patch now)"
    end
    if s.restore_skipped > 0 then
        lines[#lines + 1] = "  " .. s.restore_skipped ..
            " fixture(s) have no state here to restore"
    end
    lines[#lines + 1] = ""
    lines[#lines + 1] = "Written to:"
    lines[#lines + 1] = "  macros/" .. s.outfile .. ".xml"
    lines[#lines + 1] = ""
    lines[#lines + 1] = "Import it in the Macro pool, review it, then run it."
    lines[#lines + 1] = "Do not run it during a show."
    return table.concat(lines, "\n")
end

-- ─── console side ─────────────────────────────────────────────

local function dbg(fmt, ...)
    if DEBUG then
        gma.echo("[" .. PLUGIN_TITLE .. "] " ..
            (select("#", ...) > 0 and string.format(fmt, ...) or fmt))
    end
end

local function note(fmt, ...)
    gma.echo("[" .. PLUGIN_TITLE .. "] " ..
        (select("#", ...) > 0 and string.format(fmt, ...) or fmt))
end

local function call1(fn, ...)
    if not fn then return nil end
    local ok, v = pcall(fn, ...)
    if ok then return v end
    return nil
end

local function read_file(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local c = f:read("*a")
    f:close()
    return c
end

local function write_file(path, content)
    local f, err = io.open(path, "w")
    if not f then return false, err end
    f:write(content)
    f:close()
    return true
end

local function base_path()
    return call1(gma.show.getvar, "path") or call1(gma.show.getvar, "PATH")
end

-- Read <name>.xml, then <name>1.xml .. <name>N.xml, so a single entry covers
-- both a lone export and a "...-LAYER-" prefix spanning several files.
local function collect_sources(base, name)
    local sources = {}

    local one = read_file(base .. LAYER_DIR .. name .. ".xml")
    if one then sources[#sources + 1] = { file = name .. ".xml", xml = one } end

    for i = 1, MAX_LAYER_SCAN do
        local fname = name .. i .. ".xml"
        local c = read_file(base .. LAYER_DIR .. fname)
        if c then sources[#sources + 1] = { file = fname, xml = c } end
    end

    return sources
end

-- Current patch of every usable fixture, as the console sees it right now.
-- Missing fixtures are left out and counted separately.
local function read_current(usable)
    local current, matched, missing = {}, 0, {}
    local bar = call1(gma.gui.progress.start, PLUGIN_TITLE .. ": reading patch")
    if bar then call1(gma.gui.progress.setrange, bar, 0, #usable) end

    for i, f in ipairs(usable) do
        local h = call1(O.handle, "Fixture " .. f.id)
        if h then
            current[f.id] = call1(P.get, h, "patch")
            matched = matched + 1
        else
            missing[#missing + 1] = f
        end
        if bar and (i % 25 == 0 or i == #usable) then
            call1(gma.gui.progress.set, bar, i)
        end
    end

    if bar then call1(gma.gui.progress.stop, bar) end
    return current, matched, missing
end

local function id_list(fixtures, limit)
    local ids = {}
    for i, f in ipairs(fixtures) do
        if i > limit then
            ids[#ids + 1] = string.format("... (%d more)", #fixtures - limit)
            break
        end
        ids[#ids + 1] = tostring(f.id)
    end
    return table.concat(ids, " ")
end

-- ─── entry point ──────────────────────────────────────────────

function Start()
    -- Export/import paths are drive dependent, so pin everything to the
    -- internal drive rather than guessing at a USB drive letter.
    gma.cmd("SelectDrive 1")

    local base = base_path()
    if not base then
        gma.gui.msgbox(PLUGIN_TITLE, "Could not read the console path from gma.show.getvar.")
        return
    end

    -- Fail before doing any work rather than after parsing thousands of lines.
    local probe = base .. MACRO_DIR .. "_repatch_write_test.tmp"
    local ok, err = write_file(probe, "probe")
    if not ok then
        gma.gui.msgbox(PLUGIN_TITLE, string.format(
            "Cannot write into the macros folder.\n\n%s\n\n%s",
            base .. MACRO_DIR, tostring(err)))
        return
    end
    os.remove(probe)

    local input = gma.textinput("Layer XML file name (or '...-LAYER-' prefix)", "")
    if input == nil then
        gma.feedback(PLUGIN_TITLE .. ": cancelled.")
        return
    end
    input = M.clean_name(input)
    if not input or input == "" then
        gma.gui.msgbox(PLUGIN_TITLE,
            "Enter a file name without path or extension, e.g.\n\n" ..
            "  (LYI) TB5\n  MYSHOW-LAYER-")
        return
    end

    local sources = collect_sources(base, input)
    if #sources == 0 then
        gma.gui.msgbox(PLUGIN_TITLE, string.format(
            "No layer XML found for %q.\n\nLooked in:\n%s\n\n" ..
            "Export Layer writes to the selected drive - copy the file to the " ..
            "internal drive's fixture_layers folder first.",
            input, base .. LAYER_DIR))
        return
    end

    local lists = {}
    for _, s in ipairs(sources) do
        local fixtures, layer = M.parse_layer(s.xml)
        note("read %s: %d fixture(s), layer %q", s.file, #fixtures, tostring(layer))
        lists[#lists + 1] = fixtures
    end

    local merged, duplicates = M.merge(lists)
    local usable, unpatched, multibreak = M.classify(merged)

    if #usable == 0 then
        gma.gui.msgbox(PLUGIN_TITLE, string.format(
            "%d fixture(s) found, but none carry a DMX address.\n\n" ..
            "This looks like an unpatched export (every Address is 0). " ..
            "Export the layer from a patched showfile instead.", #merged))
        return
    end

    local current, matched, missing = read_current(usable)
    local repatch = M.repatch_lines(usable)
    local restore, restore_skipped, restore_unpatches = M.restore_lines(usable, current)

    local outname = gma.textinput("Macro XML file name to write",
        M.default_output_name(input))
    if outname == nil then
        gma.feedback(PLUGIN_TITLE .. ": cancelled.")
        return
    end
    outname = M.clean_name(outname)
    if not outname or outname == "" then
        gma.gui.msgbox(PLUGIN_TITLE, "Output file name was empty or contained a path.")
        return
    end

    -- The typed name may have lost the prefix; put it back so the macros in the
    -- pool stay identifiable even when the file was renamed.
    if outname:sub(1, #OUTPUT_PREFIX) ~= OUTPUT_PREFIX then
        outname = OUTPUT_PREFIX .. outname
    end

    local xml = M.macro_xml({
        { name  = outname .. " Repatch",
          info  = "Generated by " .. PLUGIN_TITLE .. " from " .. input,
          lines = repatch },
        { name  = outname .. " Restore",
          info  = "Patch as it was on this console before the repatch macro ran",
          lines = restore },
    })

    local outpath = base .. MACRO_DIR .. outname .. ".xml"
    local wrote, werr = write_file(outpath, xml)
    if not wrote then
        gma.gui.msgbox(PLUGIN_TITLE, "Could not write:\n\n" .. outpath ..
            "\n\n" .. tostring(werr))
        return
    end

    -- Detail goes to the System Monitor; the msgbox stays readable.
    note("wrote %s", outpath)
    if #missing > 0 then
        note("not found on this console (%d): %s", #missing, id_list(missing, 60))
    end
    if #unpatched > 0 then
        note("unpatched in XML (%d): %s", #unpatched, id_list(unpatched, 60))
    end
    if #multibreak > 0 then
        note("multi-break, skipped (%d): %s", #multibreak, id_list(multibreak, 60))
    end
    if #restore_skipped > 0 then
        note("no state to restore, not on this console (%d): %s",
            #restore_skipped, id_list(restore_skipped, 60))
    end
    if DEBUG then
        for _, line in ipairs(repatch) do dbg("repatch: %s", line) end
    end

    gma.gui.msgbox(PLUGIN_TITLE, M.summary_text({
        files           = #sources,
        total           = #merged,
        usable          = #usable,
        unpatched       = #unpatched,
        multibreak      = #multibreak,
        duplicates      = duplicates,
        matched         = matched,
        missing         = #missing,
        repatch_lines     = #repatch,
        restore_lines     = #restore,
        restore_skipped   = #restore_skipped,
        restore_unpatches = restore_unpatches,
        outfile           = outname,
    }))

    gma.feedback(string.format("%s: %d repatch / %d restore line(s) -> macros/%s.xml",
        PLUGIN_TITLE, #repatch, #restore, outname))
end

function Cleanup()
end

-- ─── test export / console entry point ────────────────────────
-- On the console gma exists, so hand back the plugin entry points.
-- Offline (plain lua) gma is nil, so expose the pure functions for testing.
if gma then
    return Start, Cleanup
else
    return M
end
